"use client";

import { createContext, useContext, useEffect, useMemo, useState } from "react";
import { ChevronDown, Globe2 } from "lucide-react";

export const languages = ["English", "हिन्दी", "বাংলা", "தமிழ்", "తెలుగు"] as const;
type Language = (typeof languages)[number];
type Key = "home" | "schemes" | "assistant" | "profile" | "settings" | "dashboard" | "schemeListing" | "aiAssistant" | "search" | "welcome" | "verifyAadhaar" | "logout" | "language" | "notifications" | "privacy" | "appearance" | "refreshChat" | "readyToHelp" | "askAbout" | "settingsSaved";
const words: Record<Language, Record<Key, string>> = {
  English: { home: "Home", schemes: "Schemes", assistant: "Assistant", profile: "Profile", settings: "Settings", dashboard: "Dashboard", schemeListing: "Scheme Listing", aiAssistant: "AI Assistant", search: "Search schemes, benefits, or help...", welcome: "Welcome, Citizen", verifyAadhaar: "Verify your Aadhaar", logout: "Logout", language: "Language", notifications: "Notifications", privacy: "Privacy", appearance: "Appearance & accessibility", refreshChat: "Refresh Chat", readyToHelp: "Ready to help", askAbout: "Ask me about schemes, eligibility, or documents.", settingsSaved: "Settings saved successfully." },
  हिन्दी: { home: "होम", schemes: "योजनाएँ", assistant: "सहायक", profile: "प्रोफ़ाइल", settings: "सेटिंग्स", dashboard: "डैशबोर्ड", schemeListing: "योजना सूची", aiAssistant: "एआई सहायक", search: "योजनाएँ, लाभ या सहायता खोजें...", welcome: "स्वागत है, नागरिक", verifyAadhaar: "अपना आधार सत्यापित करें", logout: "लॉग आउट", language: "भाषा", notifications: "सूचनाएँ", privacy: "गोपनीयता", appearance: "रूप और सुविधा", refreshChat: "चैट रीफ़्रेश करें", readyToHelp: "सहायता के लिए तैयार", askAbout: "योजनाओं, पात्रता या दस्तावेज़ों के बारे में पूछें।", settingsSaved: "सेटिंग्स सफलतापूर्वक सहेजी गईं।" },
  বাংলা: { home: "হোম", schemes: "প্রকল্প", assistant: "সহায়ক", profile: "প্রোফাইল", settings: "সেটিংস", dashboard: "ড্যাশবোর্ড", schemeListing: "প্রকল্প তালিকা", aiAssistant: "এআই সহায়ক", search: "প্রকল্প, সুবিধা বা সাহায্য খুঁজুন...", welcome: "স্বাগতম, নাগরিক", verifyAadhaar: "আপনার আধার যাচাই করুন", logout: "লগ আউট", language: "ভাষা", notifications: "বিজ্ঞপ্তি", privacy: "গোপনীয়তা", appearance: "প্রদর্শন ও সুবিধা", refreshChat: "চ্যাট রিফ্রেশ করুন", readyToHelp: "সাহায্যের জন্য প্রস্তুত", askAbout: "প্রকল্প, যোগ্যতা বা নথি সম্পর্কে জিজ্ঞাসা করুন।", settingsSaved: "সেটিংস সফলভাবে সংরক্ষিত হয়েছে।" },
  தமிழ்: { home: "முகப்பு", schemes: "திட்டங்கள்", assistant: "உதவியாளர்", profile: "சுயவிவரம்", settings: "அமைப்புகள்", dashboard: "டாஷ்போர்டு", schemeListing: "திட்டப் பட்டியல்", aiAssistant: "AI உதவியாளர்", search: "திட்டங்கள், நன்மைகள் அல்லது உதவியைத் தேடுங்கள்...", welcome: "வரவேற்கிறோம், குடிமகனே", verifyAadhaar: "உங்கள் ஆதாரைச் சரிபார்க்கவும்", logout: "வெளியேறு", language: "மொழி", notifications: "அறிவிப்புகள்", privacy: "தனியுரிமை", appearance: "தோற்றம் மற்றும் அணுகல்தன்மை", refreshChat: "அரட்டையைப் புதுப்பிக்கவும்", readyToHelp: "உதவத் தயார்", askAbout: "திட்டங்கள், தகுதி அல்லது ஆவணங்களைப் பற்றி கேளுங்கள்.", settingsSaved: "அமைப்புகள் வெற்றிகரமாகச் சேமிக்கப்பட்டன." },
  తెలుగు: { home: "హోమ్", schemes: "పథకాలు", assistant: "సహాయకుడు", profile: "ప్రొఫైల్", settings: "సెట్టింగ్‌లు", dashboard: "డాష్‌బోర్డ్", schemeListing: "పథకాల జాబితా", aiAssistant: "AI సహాయకుడు", search: "పథకాలు, ప్రయోజనాలు లేదా సహాయం వెతకండి...", welcome: "స్వాగతం, పౌరుడా", verifyAadhaar: "మీ ఆధార్‌ను ధృవీకరించండి", logout: "లాగ్ అవుట్", language: "భాష", notifications: "నోటిఫికేషన్‌లు", privacy: "గోప్యత", appearance: "రూపం మరియు అందుబాటు", refreshChat: "చాట్ రిఫ్రెష్ చేయండి", readyToHelp: "సహాయానికి సిద్ధంగా ఉంది", askAbout: "పథకాలు, అర్హత లేదా పత్రాల గురించి అడగండి.", settingsSaved: "సెట్టింగ్‌లు విజయవంతంగా సేవ్ చేయబడ్డాయి." },
};

const phrases: Record<string, Record<Language, string>> = {
  "Login or register to continue your benefit journey": { English: "Login or register to continue your benefit journey", हिन्दी: "अपने लाभ की यात्रा जारी रखने के लिए लॉगिन या पंजीकरण करें", বাংলা: "আপনার সুবিধার যাত্রা চালিয়ে যেতে লগইন বা নিবন্ধন করুন", தமிழ்: "உங்கள் நன்மைப் பயணத்தைத் தொடர உள்நுழையவும் அல்லது பதிவு செய்யவும்", తెలుగు: "మీ ప్రయోజనాల ప్రయాణాన్ని కొనసాగించడానికి లాగిన్ లేదా నమోదు చేయండి" },
  "A simple multilingual access screen with visible labels, touch-friendly inputs, and privacy-first reassurance.": { English: "A simple multilingual access screen with visible labels, touch-friendly inputs, and privacy-first reassurance.", हिन्दी: "स्पष्ट लेबल, आसान इनपुट और गोपनीयता के साथ सरल बहुभाषी प्रवेश स्क्रीन।", বাংলা: "স্পষ্ট লেবেল, সহজ ইনপুট এবং গোপনীয়তার আশ্বাসসহ একটি সহজ বহুভাষিক প্রবেশ স্ক্রিন।", தமிழ்: "தெளிவான லேபிள்கள், எளிய உள்ளீடுகள் மற்றும் தனியுரிமை பாதுகாப்புடன் கூடிய பலமொழி அணுகல் திரை.", తెలుగు: "స్పష్టమైన లేబుళ్లు, సులభమైన ఇన్‌పుట్‌లు మరియు గోప్యతా భరోసాతో సరళమైన బహుభాషా యాక్సెస్ స్క్రీన్." },
  "Citizen Account": { English: "Citizen Account", हिन्दी: "नागरिक खाता", বাংলা: "নাগরিক অ্যাকাউন্ট", தமிழ்: "குடிமக்கள் கணக்கு", తెలుగు: "పౌర ఖాతా" },
  "Login/Register": { English: "Login/Register", हिन्दी: "लॉगिन/पंजीकरण", বাংলা: "লগইন/নিবন্ধন", தமிழ்: "உள்நுழைவு/பதிவு", తెలుగు: "లాగిన్/నమోదు" },
  "Enter registered contact": { English: "Enter registered contact", हिन्दी: "पंजीकृत संपर्क दर्ज करें", বাংলা: "নিবন্ধিত যোগাযোগ লিখুন", தமிழ்: "பதிவு செய்யப்பட்ட தொடர்பை உள்ளிடவும்", తెలుగు: "నమోదిత సంప్రదింపును నమోదు చేయండి" },
  "Enter password": { English: "Enter password", हिन्दी: "पासवर्ड दर्ज करें", বাংলা: "পাসওয়ার্ড লিখুন", தமிழ்: "கடவுச்சொல்லை உள்ளிடவும்", తెలుగు: "పాస్‌వర్డ్ నమోదు చేయండి" },
  "Confirm password": { English: "Confirm password", हिन्दी: "पासवर्ड की पुष्टि करें", বাংলা: "পাসওয়ার্ড নিশ্চিত করুন", தமிழ்: "கடவுச்சொல்லை உறுதிப்படுத்தவும்", తెలుగు: "పాస్‌వర్డ్‌ను నిర్ధారించండి" },
  "Re-enter your password": { English: "Re-enter your password", हिन्दी: "अपना पासवर्ड फिर से दर्ज करें", বাংলা: "আপনার পাসওয়ার্ড আবার লিখুন", தமிழ்: "உங்கள் கடவுச்சொல்லை மீண்டும் உள்ளிடவும்", తెలుగు: "మీ పాస్‌వర్డ్‌ను మళ్లీ నమోదు చేయండి" },
  "Ask JanSeva AI...": { English: "Ask JanSeva AI...", हिन्दी: "JanSeva AI से पूछें...", বাংলা: "JanSeva AI-কে জিজ্ঞাসা করুন...", தமிழ்: "JanSeva AI-யிடம் கேளுங்கள்...", తెలుగు: "JanSeva AIని అడగండి..." },
  "Namaste! Ask me about this page, schemes, eligibility, or applications.": { English: "Namaste! Ask me about this page, schemes, eligibility, or applications.", हिन्दी: "नमस्ते! इस पेज, योजनाओं, पात्रता या आवेदनों के बारे में पूछें।", বাংলা: "নমস্কার! এই পেজ, প্রকল্প, যোগ্যতা বা আবেদন সম্পর্কে জিজ্ঞাসা করুন।", தமிழ்: "வணக்கம்! இந்தப் பக்கம், திட்டங்கள், தகுதி அல்லது விண்ணப்பங்களைப் பற்றி கேளுங்கள்.", తెలుగు: "నమస్తే! ఈ పేజీ, పథకాలు, అర్హత లేదా దరఖాస్తుల గురించి అడగండి." },
  Login: { English: "Login", हिन्दी: "लॉगिन", বাংলা: "লগইন", தமிழ்: "உள்நுழைவு", తెలుగు: "లాగిన్" },
  Register: { English: "Register", हिन्दी: "पंजीकरण", বাংলা: "নিবন্ধন", தமிழ்: "பதிவு", తెలుగు: "నమోదు" },
  Password: { English: "Password", हिन्दी: "पासवर्ड", বাংলা: "পাসওয়ার্ড", தமிழ்: "கடவுச்சொல்", తెలుగు: "పాస్‌వర్డ్" },
  "Full Name": { English: "Full Name", हिन्दी: "पूरा नाम", বাংলা: "পুরো নাম", தமிழ்: "முழுப் பெயர்", తెలుగు: "పూర్తి పేరు" },
  "Mobile number or email": { English: "Mobile number or email", हिन्दी: "मोबाइल नंबर या ईमेल", বাংলা: "মোবাইল নম্বর বা ইমেল", தமிழ்: "மொபைல் எண் அல்லது மின்னஞ்சல்", తెలుగు: "మొబైల్ నంబర్ లేదా ఇమెయిల్" },
  "Remember me": { English: "Remember me", हिन्दी: "मुझे याद रखें", বাংলা: "আমাকে মনে রাখুন", தமிழ்: "என்னை நினைவில் வைத்திருங்கள்", తెలుగు: "నన్ను గుర్తుంచుకోండి" },
  "Forgot password?": { English: "Forgot password?", हिन्दी: "पासवर्ड भूल गए?", বাংলা: "পাসওয়ার্ড ভুলে গেছেন?", தமிழ்: "கடவுச்சொல்லை மறந்துவிட்டீர்களா?", తెలుగు: "పాస్‌వర్డ్ మర్చిపోయారా?" },
  "Create account": { English: "Create account", हिन्दी: "खाता बनाएँ", বাংলা: "অ্যাকাউন্ট তৈরি করুন", தமிழ்: "கணக்கை உருவாக்கு", తెలుగు: "ఖాతా సృష్టించండి" },
  "Secure Citizen Access": { English: "Secure Citizen Access", हिन्दी: "सुरक्षित नागरिक प्रवेश", বাংলা: "নিরাপদ নাগরিক প্রবেশ", தமிழ்: "பாதுகாப்பான குடிமக்கள் அணுகல்", తెలుగు: "సురక్షిత పౌర ప్రాప్యత" },
  "Profile Setup": { English: "Profile Setup", हिन्दी: "प्रोफ़ाइल सेटअप", বাংলা: "প্রোফাইল সেটআপ", தமிழ்: "சுயவிவர அமைப்பு", తెలుగు: "ప్రొఫైల్ సెటప్" },
  "Scheme Listing": { English: "Scheme Listing", हिन्दी: "योजना सूची", বাংলা: "প্রকল্প তালিকা", தமிழ்: "திட்டப் பட்டியல்", తెలుగు: "పథకాల జాబితా" },
  "AI Assistant": { English: "AI Assistant", हिन्दी: "एआई सहायक", বাংলা: "এআই সহায়ক", தமிழ்: "AI உதவியாளர்", తెలుగు: "AI సహాయకుడు" },
  "All schemes": { English: "All schemes", हिन्दी: "सभी योजनाएँ", বাংলা: "সমস্ত প্রকল্প", தமிழ்: "அனைத்து திட்டங்கள்", తెలుగు: "అన్ని పథకాలు" },
  "View details and application process →": { English: "View details and application process →", हिन्दी: "विवरण और आवेदन प्रक्रिया देखें →", বাংলা: "বিস্তারিত ও আবেদন প্রক্রিয়া দেখুন →", தமிழ்: "விவரங்கள் மற்றும் விண்ணப்ப செயல்முறையைப் பார்க்கவும் →", తెలుగు: "వివరాలు మరియు దరఖాస్తు ప్రక్రియను చూడండి →" },
  "Type your question...": { English: "Type your question...", हिन्दी: "अपना प्रश्न लिखें...", বাংলা: "আপনার প্রশ্ন লিখুন...", தமிழ்: "உங்கள் கேள்வியை உள்ளிடுங்கள்...", తెలుగు: "మీ ప్రశ్నను టైప్ చేయండి..." },
  "Processing...": { English: "Processing...", हिन्दी: "प्रक्रिया जारी है...", বাংলা: "প্রক্রিয়া চলছে...", தமிழ்: "செயலாக்கப்படுகிறது...", తెలుగు: "ప్రాసెస్ అవుతోంది..." },
};

const extraPhrases: [string, string, string, string, string][] = [
  ["Namaste. Ask me about schemes, eligibility, or documents.", "नमस्ते। योजनाओं, पात्रता या दस्तावेज़ों के बारे में पूछें।", "নমস্কার। প্রকল্প, যোগ্যতা বা নথি সম্পর্কে জিজ্ঞাসা করুন।", "வணக்கம். திட்டங்கள், தகுதி அல்லது ஆவணங்களைப் பற்றி கேளுங்கள்.", "నమస్తే. పథకాలు, అర్హత లేదా పత్రాల గురించి అడగండి."],
  ["JanSeva Assistant", "JanSeva सहायक", "JanSeva সহায়ক", "JanSeva உதவியாளர்", "JanSeva సహాయకుడు"], ["Schemes available", "उपलब्ध योजनाएँ", "উপলব্ধ প্রকল্প", "கிடைக்கும் திட்டங்கள்", "అందుబాటులో ఉన్న పథకాలు"], ["Benefits Accessed", "प्राप्त लाभ", "পাওয়া সুবিধা", "பெற்ற நன்மைகள்", "పొందిన ప్రయోజనాలు"], ["Citizens Assisted", "सहायता प्राप्त नागरिक", "সহায়তা পাওয়া নাগরিক", "உதவி பெற்ற குடிமக்கள்", "సహాయం పొందిన పౌరులు"], ["Languages Supported", "समर्थित भाषाएँ", "সমর্থিত ভাষা", "ஆதரிக்கப்படும் மொழிகள்", "మద్దతు ఉన్న భాషలు"],
  ["Dynamic guidance powered by the current scheme and eligibility data.", "वर्तमान योजना और पात्रता डेटा से संचालित मार्गदर्शन।", "বর্তমান প্রকল্প ও যোগ্যতার তথ্যভিত্তিক নির্দেশনা।", "தற்போதைய திட்டம் மற்றும் தகுதி தரவின் அடிப்படையிலான வழிகாட்டுதல்.", "ప్రస్తుత పథకం మరియు అర్హత డేటాతో మార్గదర్శనం."],
  ["Ask JanSeva AI", "JanSeva AI से पूछें", "JanSeva AI-কে জিজ্ঞাসা করুন", "JanSeva AI-யிடம் கேளுங்கள்", "JanSeva AIని అడగండి"],
  ["PROFILE SETUP", "प्रोफ़ाइल सेटअप", "প্রোফাইল সেটআপ", "சுயவிவர அமைப்பு", "ప్రొఫైల్ సెటప్"], ["SCHEME LISTING", "योजना सूची", "প্রকল্পের তালিকা", "திட்டப் பட்டியல்", "పథకాల జాబితా"], ["AI ASSISTANT", "एआई सहायक", "এআই সহায়ক", "AI உதவியாளர்", "AI సహాయకుడు"],
  ["Date of birth", "जन्म तिथि", "জন্মতারিখ", "பிறந்த தேதி", "పుట్టిన తేదీ"], ["Gender", "लिंग", "লিঙ্গ", "பாலினம்", "లింగం"], ["Marital status", "वैवाहिक स्थिति", "বৈবাহিক অবস্থা", "திருமண நிலை", "వైవాహిక స్థితి"], ["State", "राज्य", "রাজ্য", "மாநிலம்", "రాష్ట్రం"], ["District", "ज़िला", "জেলা", "மாவட்டம்", "జిల్లా"], ["Preferred language", "पसंदीदा भाषा", "পছন্দের ভাষা", "விருப்ப மொழி", "ఇష్టమైన భాష"],
  ["Household size (e.g. 4)", "परिवार का आकार (जैसे 4)", "পরিবারের সদস্যসংখ্যা (যেমন ৪)", "குடும்ப அளவு (எ.கா. 4)", "కుటుంబ పరిమాణం (ఉదా. 4)"], ["Residence type", "निवास का प्रकार", "বাসস্থানের ধরন", "வசிப்பிட வகை", "నివాస రకం"], ["Social category", "सामाजिक श्रेणी", "সামাজিক শ্রেণি", "சமூகப் பிரிவு", "సామాజిక వర్గం"], ["Minority status", "अल्पसंख्यक स्थिति", "সংখ্যালঘু অবস্থা", "சிறுபான்மை நிலை", "మైనారిటీ స్థితి"], ["Disability status", "दिव्यांगता स्थिति", "প্রতিবন্ধিতা অবস্থা", "மாற்றுத்திறன் நிலை", "వైకల్య స్థితి"], ["House ownership", "घर का स्वामित्व", "বাড়ির মালিকানা", "வீட்டு உரிமை", "ఇంటి యాజమాన్యం"], ["Ration card type", "राशन कार्ड का प्रकार", "রেশন কার্ডের ধরন", "ரேஷன் அட்டை வகை", "రేషన్ కార్డు రకం"], ["Primary need", "प्राथमिक आवश्यकता", "প্রধান প্রয়োজন", "முதன்மை தேவை", "ప్రధాన అవసరం"],
  ["Annual family income", "वार्षिक पारिवारिक आय", "বার্ষিক পারিবারিক আয়", "ஆண்டு குடும்ப வருமானம்", "వార్షిక కుటుంబ ఆదాయం"], ["Primary occupation", "मुख्य व्यवसाय", "প্রধান পেশা", "முதன்மை தொழில்", "ప్రధాన వృత్తి"], ["Employment status", "रोज़गार की स्थिति", "কর্মসংস্থানের অবস্থা", "வேலை நிலை", "ఉపాధి స్థితి"], ["Highest education level", "उच्चतम शिक्षा स्तर", "সর্বোচ্চ শিক্ষার স্তর", "உயர்ந்த கல்வி நிலை", "అత్యున్నత విద్యా స్థాయి"], ["Landholding (if applicable)", "भूमि स्वामित्व (यदि लागू हो)", "জমির মালিকানা (প্রযোজ্য হলে)", "நில உரிமை (பொருந்தினால்)", "భూమి కలిగి ఉండటం (వర్తిస్తే)"], ["Bank account status", "बैंक खाते की स्थिति", "ব্যাংক অ্যাকাউন্টের অবস্থা", "வங்கிக் கணக்கு நிலை", "బ్యాంక్ ఖాతా స్థితి"], ["LPG connection", "एलपीजी कनेक्शन", "এলপিজি সংযোগ", "LPG இணைப்பு", "LPG కనెక్షన్"], ["I have a valid Aadhaar card", "मेरे पास वैध आधार कार्ड है", "আমার বৈধ আধার কার্ড আছে", "என்னிடம் செல்லுபடியாகும் ஆதார் அட்டை உள்ளது", "నా వద్ద చెల్లుబాటు అయ్యే ఆధార్ కార్డు ఉంది"],
  ["Male", "पुरुष", "পুরুষ", "ஆண்", "పురుషుడు"], ["Female", "महिला", "মহিলা", "பெண்", "స్త్రీ"], ["Prefer not to say", "कहना पसंद नहीं", "জানাতে চাই না", "சொல்ல விரும்பவில்லை", "చెప్పకూడదని కోరుకుంటున్నాను"], ["light", "लाइट", "লাইট", "லைட்", "లైట్"], ["dark", "डार्क", "ডার্ক", "டார்க்", "డార్క్"], ["system", "सिस्टम", "সিস্টেম", "சிஸ்டம்", "సిస్టమ్"],
  ["Based on your saved profile", "आपकी सहेजी गई प्रोफ़ाइल के आधार पर", "আপনার সংরক্ষিত প্রোফাইলের ভিত্তিতে", "சேமிக்கப்பட்ட சுயவிவரத்தின் அடிப்படையில்", "మీ సేవ్ చేసిన ప్రొఫైల్ ఆధారంగా"], ["Complete your profile to get matches", "मिलान पाने के लिए अपनी प्रोफ़ाइल पूरी करें", "মিল পেতে আপনার প্রোফাইল সম্পূর্ণ করুন", "பொருத்தங்களைப் பெற சுயவிவரத்தை முடிக்கவும்", "సరిపోలికలు పొందడానికి మీ ప్రొఫైల్ పూర్తి చేయండి"], ["Location matches your profile", "स्थान आपकी प्रोफ़ाइल से मेल खाता है", "অবস্থান আপনার প্রোফাইলের সঙ্গে মেলে", "இருப்பிடம் உங்கள் சுயவிவரத்துடன் பொருந்துகிறது", "స్థానం మీ ప్రొఫైల్‌తో సరిపోలుతోంది"], ["Open year-round", "पूरे वर्ष खुला", "সারা বছর খোলা", "ஆண்டு முழுவதும் திறந்திருக்கும்", "ఏడాది పొడవునా తెరిచి ఉంటుంది"], ["Next installment cycle", "अगली किस्त का चक्र", "পরবর্তী কিস্তির সময়কাল", "அடுத்த தவணைச் சுழற்சி", "తదుపరి వాయిదా చక్రం"], ["State-wise window", "राज्यवार अवधि", "রাজ্যভিত্তিক সময়সীমা", "மாநில வாரியான காலம்", "రాష్ట్రాల వారీ సమయం"], ["Aadhaar-ready application", "आधार-तैयार आवेदन", "আধার-প্রস্তুত আবেদন", "ஆதார் தயார் விண்ணப்பம்", "ఆధార్ సిద్ధమైన దరఖాస్తు"], ["Income band appears relevant", "आय सीमा प्रासंगिक लगती है", "আয়ের সীমা প্রাসঙ্গিক মনে হচ্ছে", "வருமான வரம்பு பொருத்தமாக உள்ளது", "ఆదాయ పరిధి సంబంధితంగా ఉంది"],
  ["Details", "विवरण", "বিবরণ", "விவரங்கள்", "వివరాలు"], ["Profile details match", "प्रोफ़ाइल विवरण मेल खाते हैं", "প্রোফাইলের তথ্য মিলে যায়", "சுயவிவர விவரங்கள் பொருந்துகின்றன", "ప్రొఫైల్ వివరాలు సరిపోతున్నాయి"], ["Add your state", "अपना राज्य जोड़ें", "আপনার রাজ্য যোগ করুন", "உங்கள் மாநிலத்தைச் சேர்க்கவும்", "మీ రాష్ట్రాన్ని జోడించండి"], ["Complete more profile details to see personalized matches.", "व्यक्तिगत मिलान देखने के लिए प्रोफ़ाइल की अधिक जानकारी पूरी करें।", "ব্যক্তিগত মিল দেখতে আরও প্রোফাইলের তথ্য সম্পূর্ণ করুন।", "தனிப்பயன் பொருத்தங்களைக் காண மேலும் சுயவிவர விவரங்களை முடிக்கவும்.", "వ్యక్తిగత సరిపోలికలు చూడటానికి మరిన్ని ప్రొఫైల్ వివరాలు పూర్తి చేయండి."], ["Your core eligibility details are complete.", "आपकी मुख्य पात्रता जानकारी पूरी है।", "আপনার মূল যোগ্যতার তথ্য সম্পূর্ণ হয়েছে।", "உங்கள் முக்கிய தகுதி விவரங்கள் முடிந்துவிட்டன.", "మీ ప్రధాన అర్హత వివరాలు పూర్తయ్యాయి."], ["No applications saved yet.", "अभी तक कोई आवेदन सहेजा नहीं गया।", "এখনও কোনো আবেদন সংরক্ষিত হয়নি।", "இதுவரை விண்ணப்பங்கள் சேமிக்கப்படவில்லை.", "ఇంకా దరఖాస్తులు సేవ్ చేయబడలేదు."],
  ["Government of India Initiative", "भारत सरकार की पहल", "ভারত সরকারের উদ্যোগ", "இந்திய அரசின் முயற்சி", "భారత ప్రభుత్వ చొరవ"],
  ["Find government benefits", "सरकारी लाभ खोजें", "সরকারি সুবিধা খুঁজুন", "அரசு நன்மைகளைக் கண்டறியுங்கள்", "ప్రభుత్వ ప్రయోజనాలను కనుగొనండి"],
  ["you are eligible for", "जिनके लिए आप पात्र हैं", "যেগুলির জন্য আপনি যোগ্য", "நீங்கள் தகுதியுடையவை", "మీరు అర్హత పొందినవి"],
  ["Navigate Indian welfare schemes with a clear multilingual interface that helps citizens discover, understand, and prepare applications.", "स्पष्ट बहुभाषी इंटरफ़ेस के साथ भारतीय कल्याण योजनाएँ खोजें, समझें और आवेदन तैयार करें।", "স্পষ্ট বহুভাষিক ইন্টারফেসে ভারতীয় কল্যাণ প্রকল্প খুঁজুন, বুঝুন এবং আবেদন প্রস্তুত করুন।", "தெளிவான பலமொழி இடைமுகம் மூலம் இந்திய நலத்திட்டங்களைக் கண்டறிந்து விண்ணப்பங்களைத் தயாரிக்கவும்.", "స్పష్టమైన బహుభాషా ఇంటర్‌ఫేస్‌తో భారతీయ సంక్షేమ పథకాలను కనుగొని, అర్థం చేసుకుని దరఖాస్తులు సిద్ధం చేయండి."],
  ["Get Started", "शुरू करें", "শুরু করুন", "தொடங்குங்கள்", "ప్రారంభించండి"], ["How it works", "यह कैसे काम करता है", "এটি কীভাবে কাজ করে", "இது எவ்வாறு செயல்படுகிறது", "ఇది ఎలా పనిచేస్తుంది"],
  ["Online and ready", "ऑनलाइन और तैयार", "অনলাইন এবং প্রস্তুত", "ஆன்லைனில் தயார்", "ఆన్‌లైన్‌లో సిద్ధంగా ఉంది"],
  ["Namaste. I can help you find benefits for education, health, housing, and farming.", "नमस्ते। मैं शिक्षा, स्वास्थ्य, आवास और खेती के लाभ खोजने में आपकी सहायता कर सकता हूँ।", "নমস্কার। শিক্ষা, স্বাস্থ্য, আবাসন এবং কৃষির সুবিধা খুঁজে পেতে আমি সাহায্য করতে পারি।", "வணக்கம். கல்வி, சுகாதாரம், வீடு மற்றும் விவசாய நன்மைகளைக் கண்டறிய உதவுகிறேன்.", "నమస్తే. విద్య, ఆరోగ్యం, గృహనిర్మాణం మరియు వ్యవసాయ ప్రయోజనాలను కనుగొనడంలో నేను సహాయపడతాను."],
  ["Approved Benefits", "स्वीकृत लाभ", "অনুমোদিত সুবিধা", "அங்கீகரிக்கப்பட்ட நன்மைகள்", "ఆమోదించబడిన ప్రయోజనాలు"], ["Registered Citizens", "पंजीकृत नागरिक", "নিবন্ধিত নাগরিক", "பதிவு செய்யப்பட்ட குடிமக்கள்", "నమోదైన పౌరులు"], ["Schemes Indexed", "सूचीबद्ध योजनाएँ", "তালিকাভুক্ত প্রকল্প", "பட்டியலிடப்பட்ட திட்டங்கள்", "సూచికలోని పథకాలు"], ["Languages Available", "उपलब्ध भाषाएँ", "উপলব্ধ ভাষা", "கிடைக்கும் மொழிகள்", "అందుబాటులో ఉన్న భాషలు"],
  ["Smarter bureaucracy, better living", "बेहतर प्रशासन, बेहतर जीवन", "স্মার্ট প্রশাসন, উন্নত জীবন", "சிறந்த நிர்வாகம், சிறந்த வாழ்க்கை", "మెరుగైన పాలన, మెరుగైన జీవితం"],
  ["Designed for every citizen, with responsive pages and multilingual UI patterns.", "हर नागरिक के लिए उत्तरदायी पेज और बहुभाषी इंटरफ़ेस के साथ बनाया गया।", "প্রতিটি নাগরিকের জন্য প্রতিক্রিয়াশীল পেজ ও বহুভাষিক ইন্টারফেসসহ তৈরি।", "ஒவ்வொரு குடிமகனுக்காகவும் பதிலளிக்கும் பக்கங்கள் மற்றும் பலமொழி இடைமுகத்துடன் வடிவமைக்கப்பட்டது.", "ప్రతి పౌరుడి కోసం స్పందించే పేజీలు మరియు బహుభాషా UIతో రూపొందించబడింది."],
  ["Instant Eligibility Matching", "तुरंत पात्रता मिलान", "তাৎক্ষণিক যোগ্যতা মিলানো", "உடனடி தகுதி பொருத்தம்", "తక్షణ అర్హత సరిపోలిక"], ["Regional Language UI", "क्षेत्रीय भाषा इंटरफ़ेस", "আঞ্চলিক ভাষার ইন্টারফেস", "பிராந்திய மொழி இடைமுகம்", "ప్రాంతీయ భాషా ఇంటర్‌ఫేస్"], ["Privacy-first Forms", "गोपनीयता-केंद्रित फ़ॉर्म", "গোপনীয়তা-কেন্দ্রিক ফর্ম", "தனியுரிமை முன்னுரிமை படிவங்கள்", "గోప్యతకు ప్రాధాన్యమిచ్చే ఫారమ్‌లు"],
  ["Explore government schemes", "सरकारी योजनाएँ देखें", "সরকারি প্রকল্প দেখুন", "அரசுத் திட்டங்களை ஆராயுங்கள்", "ప్రభుత్వ పథకాలను అన్వేషించండి"], ["Browse all available benefits. Complete your profile after choosing a scheme to see your eligibility.", "सभी उपलब्ध लाभ देखें। अपनी पात्रता देखने के लिए योजना चुनने के बाद प्रोफ़ाइल पूरी करें।", "সমস্ত উপলব্ধ সুবিধা দেখুন। যোগ্যতা দেখতে প্রকল্প বেছে নিয়ে প্রোফাইল সম্পূর্ণ করুন।", "கிடைக்கும் அனைத்து நன்மைகளையும் பாருங்கள். தகுதியைக் காண திட்டத்தைத் தேர்ந்தெடுத்து சுயவிவரத்தை முடிக்கவும்.", "అందుబాటులో ఉన్న అన్ని ప్రయోజనాలను చూడండి. అర్హతను చూడటానికి పథకాన్ని ఎంచుకున్న తర్వాత మీ ప్రొఫైల్ పూర్తి చేయండి."],
  ["Search schemes by name or category...", "नाम या श्रेणी से योजनाएँ खोजें...", "নাম বা বিভাগ দিয়ে প্রকল্প খুঁজুন...", "பெயர் அல்லது வகை மூலம் திட்டங்களைத் தேடுங்கள்...", "పేరు లేదా వర్గం ద్వారా పథకాలను వెతకండి..."], ["Schemes you may be eligible for", "वे योजनाएँ जिनके लिए आप पात्र हो सकते हैं", "আপনি যে প্রকল্পগুলির জন্য যোগ্য হতে পারেন", "நீங்கள் தகுதியுடைய திட்டங்கள்", "మీరు అర్హత పొందగల పథకాలు"], ["All schemes", "सभी योजनाएँ", "সমস্ত প্রকল্প", "அனைத்து திட்டங்கள்", "అన్ని పథకాలు"],
  ["Profile-based scheme matches", "प्रोफ़ाइल आधारित योजना मिलान", "প্রোফাইল-ভিত্তিক প্রকল্পের মিল", "சுயவிவர அடிப்படையிலான திட்டப் பொருத்தங்கள்", "ప్రొఫైల్ ఆధారిత పథక సరిపోలికలు"], ["schemes found", "योजनाएँ मिलीं", "প্রকল্প পাওয়া গেছে", "திட்டங்கள் கிடைத்தன", "పథకాలు కనుగొనబడ్డాయి"], ["Explore Schemes", "योजनाएँ देखें", "প্রকল্প দেখুন", "திட்டங்களை ஆராயுங்கள்", "పథకాలను అన్వేషించండి"], ["Profile Completion", "प्रोफ़ाइल पूर्णता", "প্রোফাইল সম্পূর্ণতা", "சுயவிவர நிறைவு", "ప్రొఫైల్ పూర్తి"], ["Eligible Schemes", "पात्र योजनाएँ", "যোগ্য প্রকল্প", "தகுதியான திட்டங்கள்", "అర్హత ఉన్న పథకాలు"], ["View All", "सभी देखें", "সব দেখুন", "அனைத்தையும் பார்க்கவும்", "అన్నింటినీ చూడండి"], ["Profile checklist", "प्रोफ़ाइल चेकलिस्ट", "প্রোফাইল চেকলিস্ট", "சுயவிவர சரிபார்ப்புப் பட்டியல்", "ప్రొఫైల్ చెక్‌లిస్ట్"], ["Recent Applications", "हाल के आवेदन", "সাম্প্রতিক আবেদন", "சமீபத்திய விண்ணப்பங்கள்", "ఇటీవలి దరఖాస్తులు"], ["No applications saved yet.", "अभी तक कोई आवेदन सहेजा नहीं गया।", "এখনও কোনো আবেদন সংরক্ষিত হয়নি।", "இதுவரை விண்ணப்பங்கள் சேமிக்கப்படவில்லை.", "ఇంకా దరఖాస్తులు సేవ్ చేయబడలేదు."],
  ["Complete your citizen profile", "अपनी नागरिक प्रोफ़ाइल पूरी करें", "আপনার নাগরিক প্রোফাইল সম্পূর্ণ করুন", "உங்கள் குடிமக்கள் சுயவிவரத்தை முடிக்கவும்", "మీ పౌర ప్రొఫైల్‌ను పూర్తి చేయండి"], ["Profile Readiness", "प्रोफ़ाइल तैयारी", "প্রোফাইল প্রস্তুতি", "சுயவிவரத் தயார்நிலை", "ప్రొఫైల్ సిద్ధత"], ["Document Checklist", "दस्तावेज़ चेकलिस्ट", "নথির চেকলিস্ট", "ஆவண சரிபார்ப்புப் பட்டியல்", "పత్రాల చెక్‌లిస్ట్"], ["Identity", "पहचान", "পরিচয়", "அடையாளம்", "గుర్తింపు"], ["Household", "परिवार", "পরিবার", "குடும்பம்", "కుటుంబం"], ["Income and occupation", "आय और व्यवसाय", "আয় ও পেশা", "வருமானம் மற்றும் தொழில்", "ఆదాయం మరియు వృత్తి"], ["Save Draft", "ड्राफ्ट सहेजें", "খসড়া সংরক্ষণ করুন", "வரைவைச் சேமிக்கவும்", "డ్రాఫ్ట్ సేవ్ చేయండి"], ["View Dashboard", "डैशबोर्ड देखें", "ড্যাশবোর্ড দেখুন", "டாஷ்போர்டைப் பார்க்கவும்", "డాష్‌బోర్డ్ చూడండి"],
  ["Preferences and accessibility", "प्राथमिकताएँ और सुविधा", "পছন্দ ও অ্যাক্সেসিবিলিটি", "விருப்பங்கள் மற்றும் அணுகல்தன்மை", "ప్రాధాన్యతలు మరియు అందుబాటు"], ["Your preferences are saved to your JanSeva account and apply across devices.", "आपकी प्राथमिकताएँ आपके JanSeva खाते में सहेजी जाती हैं और सभी उपकरणों पर लागू होती हैं।", "আপনার পছন্দগুলি আপনার JanSeva অ্যাকাউন্টে সংরক্ষিত হয় এবং সব ডিভাইসে প্রযোজ্য।", "உங்கள் விருப்பங்கள் உங்கள் JanSeva கணக்கில் சேமிக்கப்பட்டு அனைத்து சாதனங்களிலும் பயன்படுத்தப்படும்.", "మీ ప్రాధాన్యతలు మీ JanSeva ఖాతాలో సేవ్ చేయబడి అన్ని పరికరాల్లో వర్తిస్తాయి."],
  ["Scheme deadline alerts", "योजना की अंतिम तिथि की सूचनाएँ", "প্রকল্পের সময়সীমার সতর্কতা", "திட்ட காலக்கெடு எச்சரிக்கைகள்", "పథక గడువు హెచ్చరికలు"], ["New eligibility matches", "नई पात्रता मिलान", "নতুন যোগ্যতার মিল", "புதிய தகுதி பொருத்தங்கள்", "కొత్త అర్హత సరిపోలికలు"], ["Application status updates", "आवेदन स्थिति अपडेट", "আবেদনের স্থিতি আপডেট", "விண்ணப்ப நிலை புதுப்பிப்புகள்", "దరఖాస్తు స్థితి నవీకరణలు"], ["Show sensitive benefit amounts", "संवेदनशील लाभ राशि दिखाएँ", "সংবেদনশীল সুবিধার পরিমাণ দেখান", "முக்கியமான நன்மைத் தொகைகளைக் காட்டவும்", "సున్నితమైన ప్రయోజన మొత్తాలను చూపించండి"], ["Allow profile completion reminders", "प्रोफ़ाइल पूर्णता अनुस्मारक की अनुमति दें", "প্রোফাইল সম্পূর্ণতার অনুস্মারক অনুমোদন করুন", "சுயவிவர நிறைவு நினைவூட்டல்களை அனுமதிக்கவும்", "ప్రొఫైల్ పూర్తి రిమైండర్‌లను అనుమతించండి"], ["Compact dashboard cards", "कॉम्पैक्ट डैशबोर्ड कार्ड", "কমপ্যাক্ট ড্যাশবোর্ড কার্ড", "சுருக்கமான டாஷ்போர்டு அட்டைகள்", "కాంపాక్ట్ డాష్‌బోర్డ్ కార్డులు"], ["High contrast focus states", "उच्च कंट्रास्ट फ़ोकस स्थिति", "উচ্চ কনট্রাস্ট ফোকাস অবস্থা", "உயர் மாறுபாடு கவன நிலைகள்", "అధిక కాంట్రాస్ట్ ఫోకస్ స్థితులు"], ["Larger form labels", "बड़े फ़ॉर्म लेबल", "বড় ফর্ম লেবেল", "பெரிய படிவ லேபிள்கள்", "పెద్ద ఫారమ్ లేబుల్‌లు"],
];
extraPhrases.forEach(([english, ...translated]) => { phrases[english] = Object.fromEntries(languages.map((language, index) => [language, translated[index]])) as Record<Language, string>; });

const originals = new WeakMap<Text, string>();
const attributes = new WeakMap<Element, Record<string, string>>();
const translated = (original: string, next: Language) => { const phrase = Object.keys(phrases).find((item) => item.toLowerCase() === original.toLowerCase()); const key = Object.keys(words.English).find((item) => words.English[item as Key].toLowerCase() === original.toLowerCase()); return phrases[phrase || original]?.[next] || (key ? words[next][key as Key] : original); };

const Context = createContext<{ language: Language; setLanguage: (language: Language) => void; t: (key: Key) => string }>({ language: "English", setLanguage: () => {}, t: (key) => words.English[key] });

export function LanguageProvider({ children }: { children: React.ReactNode }) {
  const [language, setLanguageState] = useState<Language>("English");
  useEffect(() => { const saved = localStorage.getItem("janseva-language") as Language; if (languages.includes(saved)) { setLanguageState(saved); return; } fetch("/api/settings").then((r) => r.ok ? r.json() : null).then((data) => data?.language && languages.includes(data.language) && setLanguageState(data.language)); }, []);
  const translatePage = (next: Language) => { const walker = document.createTreeWalker(document.body, NodeFilter.SHOW_TEXT); let node: Node | null; while ((node = walker.nextNode())) { const textNode = node as Text; const original = originals.get(textNode) || textNode.textContent?.trim(); if (!original) continue; originals.set(textNode, original); const value = translated(original, next); if (textNode.textContent !== value) textNode.textContent = value; } document.querySelectorAll<HTMLElement>("[placeholder], [aria-label], [title]").forEach((element) => { const saved = attributes.get(element) || {}; attributes.set(element, saved); ["placeholder", "aria-label", "title"].forEach((name) => { const original = saved[name] || element.getAttribute(name); if (!original) return; saved[name] = original; element.setAttribute(name, translated(original, next)); }); }); };
  const setLanguage = (next: Language) => { setLanguageState(next); localStorage.setItem("janseva-language", next); document.documentElement.lang = next; translatePage(next); fetch("/api/settings", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ language: next }) }); };
  const value = useMemo(() => ({ language, setLanguage, t: (key: Key) => words[language][key] }), [language]);
  useEffect(() => { translatePage(language); const observer = new MutationObserver(() => translatePage(language)); observer.observe(document.body, { childList: true, subtree: true }); return () => observer.disconnect(); }, [language]);
  return <Context.Provider value={value}>{children}</Context.Provider>;
}

export const useLanguage = () => useContext(Context);

export function LanguageSwitcher() {
  const { language, setLanguage } = useLanguage();
  const [open, setOpen] = useState(false);
  return <div className="relative"><button type="button" aria-label={`Language: ${language}`} onClick={() => setOpen(!open)} className="flex items-center gap-2 rounded-full border border-outline-variant bg-white px-3 py-2 text-sm text-on-surface-variant"><Globe2 size={18} /><span>{language}</span><ChevronDown size={16} /></button>{open && <div className="absolute right-0 top-12 z-[80] min-w-36 rounded-xl border border-outline-variant bg-white p-1 shadow-xl">{languages.map((item) => <button key={item} type="button" aria-current={item === language} onClick={() => { setLanguage(item); setOpen(false); }} className={`block w-full rounded-lg px-3 py-2 text-left text-sm ${item === language ? "bg-primary text-white" : "hover:bg-surface-container-low"}`}>{item}</button>)}</div>}</div>;
}
