"use client";

import { useEffect, useState } from "react";
import { Bell, Globe2, Moon, ShieldCheck, Sun, Laptop } from "lucide-react";
import { Card } from "@/components/ui";
import { useLanguage } from "@/components/language-provider";

type Settings = { theme: string; notificationsSchemes: boolean; notificationsMatches: boolean; notificationsApplications: boolean; showSensitiveAmounts: boolean; profileReminders: boolean; compactDashboard: boolean; highContrast: boolean; largerLabels: boolean };
const defaults: Settings = { theme: "system", notificationsSchemes: true, notificationsMatches: true, notificationsApplications: false, showSensitiveAmounts: true, profileReminders: false, compactDashboard: false, highContrast: true, largerLabels: false };

export default function SettingsForm() {
  const [settings, setSettings] = useState(defaults);
  const [language, setLanguage] = useState("English");
  const [saved, setSaved] = useState(false);
  const { setLanguage: setAppLanguage } = useLanguage();
  useEffect(() => { fetch("/api/settings").then((r) => r.ok ? r.json() : null).then((data) => data && (setSettings(data.settings), setLanguage(data.language))); }, []);
  const save = (next: Partial<Settings> & { language?: string }) => { const merged = { ...settings, ...next }; setSettings(merged); if (next.language) setAppLanguage(next.language as Parameters<typeof setAppLanguage>[0]); setSaved(false); fetch("/api/settings", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ ...merged, language: next.language || language }) }).then(() => setSaved(true)); if (next.theme) dispatchEvent(new CustomEvent("janseva-theme", { detail: next.theme })); };
  return <div className="mt-8 grid gap-6 lg:grid-cols-2"><Card><Header icon={<Globe2 size={22} />} title="Language" /><div className="flex flex-wrap gap-2">{["English", "हिन्दी", "বাংলা", "தமிழ்", "తెలుగు"].map((item) => <button key={item} type="button" onClick={() => save({ language: item })} className={`rounded-full border px-3 py-1 text-xs font-semibold ${language === item ? "border-primary bg-primary text-white" : "border-outline-variant"}`}>{item}</button>)}</div><p className="mt-4 text-xs text-on-surface-variant">Selected: {language}</p></Card><Card><Header icon={<Bell size={22} />} title="Notifications" /><Toggle label="Scheme deadline alerts" value={settings.notificationsSchemes} onChange={(value) => save({ notificationsSchemes: value })} /><Toggle label="New eligibility matches" value={settings.notificationsMatches} onChange={(value) => save({ notificationsMatches: value })} /><Toggle label="Application status updates" value={settings.notificationsApplications} onChange={(value) => save({ notificationsApplications: value })} /></Card><Card><Header icon={<ShieldCheck size={22} />} title="Privacy" /><Toggle label="Show sensitive benefit amounts" value={settings.showSensitiveAmounts} onChange={(value) => save({ showSensitiveAmounts: value })} /><Toggle label="Allow profile completion reminders" value={settings.profileReminders} onChange={(value) => save({ profileReminders: value })} /></Card><Card><Header icon={<Moon size={22} />} title="Appearance & accessibility" /><div className="mb-4 flex gap-2">{[[Sun, "light"], [Moon, "dark"], [Laptop, "system"]].map(([Icon, value]) => <button key={String(value)} type="button" onClick={() => save({ theme: String(value) })} className={`flex flex-1 items-center justify-center gap-2 rounded-lg border p-3 text-sm font-semibold ${settings.theme === value ? "border-primary bg-primary text-white" : "border-outline-variant"}`}><Icon size={16} />{String(value)}</button>)}</div><Toggle label="Compact dashboard cards" value={settings.compactDashboard} onChange={(value) => save({ compactDashboard: value })} /><Toggle label="High contrast focus states" value={settings.highContrast} onChange={(value) => save({ highContrast: value })} /><Toggle label="Larger form labels" value={settings.largerLabels} onChange={(value) => save({ largerLabels: value })} /></Card>{saved && <p className="text-sm font-semibold text-secondary lg:col-span-2">Settings saved successfully.</p>}</div>;
}

function Header({ icon, title }: { icon: React.ReactNode; title: string }) { return <div className="mb-5 flex items-center gap-3"><div className="flex h-10 w-10 items-center justify-center rounded-xl bg-primary-fixed text-primary">{icon}</div><h2 className="text-xl font-bold">{title}</h2></div>; }
function Toggle({ label, value, onChange }: { label: string; value: boolean; onChange: (value: boolean) => void }) { return <label className="mb-4 flex cursor-pointer items-center justify-between rounded-xl bg-surface-container-low p-4 last:mb-0"><span className="text-sm font-semibold">{label}</span><input type="checkbox" checked={value} onChange={(e) => onChange(e.target.checked)} className="h-5 w-5 rounded border-outline-variant text-primary" /></label>; }
